version: "3"
networks:
  auctiondev:
    driver: bridge
volumes:
  mongodb_data:
services:
  # Node code
  auctiondev:
    container_name: auctiondev
    restart: always
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    ports:
      - "4040:4040"
    environment:
      - NODE_ENV=development
      - PORT=4040
      - MONGO_URI=mongodb://auctiondbdev:27017/auction 
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - nginxdev
      - auctiondbdev
    # links:
    #   - nginxdev
    #   - auctiondbdev
    networks:
      - auctiondev
  # Nginx
  nginxdev:
    image: nginx:stable-alpine
    container_name: nginxdev
    restart: always
    ports:
      - "88:80"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ./docker/dev/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - auctiondev
  # MongoDb
  auctiondbdev:
    container_name: auctiondbdev
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always
    networks:
      - auctiondev
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
